apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q275p1ogm-java-springboot 
  janus-idp.io/tekton: q275p1ogm-java-springboot
  backstage.io/kubernetes-id: q275p1ogm-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q275p1ogm-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml